# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-02 08:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='proposalassessment',
            unique_together=set([('proposal',)]),
        ),
    ]
