# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-12 05:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0008_annualadmissionapplication_authoriseduserapplication_mooringlicenseapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='VesselDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rego_no', models.CharField(max_length=200)),
                ('vessel_name', models.CharField(max_length=400)),
                ('vessel_size', models.DecimalField(decimal_places=2, default='0.00', max_digits=8)),
                ('vessel_draft', models.DecimalField(decimal_places=2, default='0.00', max_digits=8)),
                ('vessel_beam', models.DecimalField(decimal_places=2, default='0.00', max_digits=8)),
                ('vessel_weight', models.DecimalField(decimal_places=2, default='0.00', max_digits=8)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Vessel Details',
            },
        ),
        migrations.CreateModel(
            name='VesselRelations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rego_no', models.CharField(max_length=200)),
                ('vessel_name', models.CharField(max_length=400)),
                ('vessel_size', models.DecimalField(decimal_places=2, default='0.00', max_digits=8)),
                ('vessel_draft', models.DecimalField(decimal_places=2, default='0.00', max_digits=8)),
                ('vessel_beam', models.DecimalField(decimal_places=2, default='0.00', max_digits=8)),
                ('vessel_weight', models.DecimalField(decimal_places=2, default='0.00', max_digits=8)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('proposal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mooringlicensing.Proposal')),
                ('vessel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mooringlicensing.VesselDetail')),
            ],
            options={
                'verbose_name_plural': 'Vessel Relations',
            },
        ),
        migrations.CreateModel(
            name='VesselSizeCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_size', models.DecimalField(decimal_places=2, default='0.00', max_digits=8)),
                ('end_size', models.DecimalField(decimal_places=2, default='0.00', max_digits=8)),
                ('status', models.SmallIntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Vessel Size Categories',
            },
        ),
        migrations.RenameModel(
            old_name='MooringLicenseApplication',
            new_name='MooringLicenceApplication',
        ),
        migrations.RemoveField(
            model_name='vessel',
            name='proposal',
        ),
        migrations.RemoveField(
            model_name='checklistquestion',
            name='application_type',
        ),
        migrations.RemoveField(
            model_name='proposalstandardrequirement',
            name='application_type',
        ),
        migrations.RemoveField(
            model_name='question',
            name='application_type',
        ),
        migrations.AlterField(
            model_name='helppage',
            name='application_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='helppage',
            unique_together=set([('help_type', 'version')]),
        ),
        migrations.DeleteModel(
            name='ApplicationType',
        ),
        migrations.DeleteModel(
            name='Vessel',
        ),
    ]
