# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-12 05:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0009_auto_20210312_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helppage',
            name='application_type',
        ),
    ]
