# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-12 06:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0011_auto_20210312_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='replaced_by',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replace', to='mooringlicensing.Approval'),
        ),
    ]
