# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-12 06:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0012_auto_20210312_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitingListAllocation',
            fields=[
                ('approval', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mooringlicensing.Approval')),
            ],
            bases=('mooringlicensing.approval',),
        ),
    ]
