# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-23 03:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0020_auto_20210323_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vesselregistrationdocument',
            name='vesseldetailsownership',
        ),
        migrations.AddField(
            model_name='vesselregistrationdocument',
            name='proposal',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='vessel_registration_documents', to='mooringlicensing.Proposal'),
            preserve_default=False,
        ),
    ]
