# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-24 01:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0024_auto_20210324_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='vesselownership',
            name='berth_mooring',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
