# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-24 07:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0025_vesselownership_berth_mooring'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vesselownership',
            unique_together=set([('owner', 'vessel')]),
        ),
    ]
