# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-24 07:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0027_auto_20210324_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='emailuser',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
