# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-26 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0029_applicationfee'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationfee',
            name='invoice_reference',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
