# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-25 07:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0031_remove_proposal_vessel_details_many'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='org_name',
        ),
        migrations.RemoveField(
            model_name='vesselownership',
            name='berth_mooring',
        ),
        migrations.RemoveField(
            model_name='vesselownership',
            name='editable',
        ),
        migrations.AddField(
            model_name='proposal',
            name='berth_mooring',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='proposal',
            name='vessel_beam',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=8),
        ),
        migrations.AddField(
            model_name='proposal',
            name='vessel_draft',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=8),
        ),
        migrations.AddField(
            model_name='proposal',
            name='vessel_length',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=8),
        ),
        migrations.AddField(
            model_name='proposal',
            name='vessel_name',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='proposal',
            name='vessel_overall_length',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=8),
        ),
        migrations.AddField(
            model_name='proposal',
            name='vessel_ownership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mooringlicensing.VesselOwnership'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='vessel_type',
            field=models.CharField(blank=True, choices=[('yacht', 'Yacht'), ('cabin_cruiser', 'Cabin Cruiser'), ('tender', 'Tender'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='proposal',
            name='vessel_weight',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=8),
        ),
        migrations.AddField(
            model_name='vesseldetails',
            name='berth_mooring',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='vesselownership',
            name='exported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vesselownership',
            name='org_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
