# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-25 09:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0033_auto_20210325_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='vesseldetails',
            name='blocking_proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mooringlicensing.Proposal'),
        ),
        migrations.AlterField(
            model_name='vesseldetails',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('draft', 'Draft'), ('old', 'Old'), ('declined', 'Declined')], default='draft', max_length=50),
        ),
    ]
