# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-29 07:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0039_auto_20210329_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='proposal_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mooringlicensing.ProposalType'),
        ),
    ]
