# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-29 08:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0043_auto_20210329_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeSeasonApplicationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mooringlicensing.ApplicationType')),
                ('fee_season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mooringlicensing.FeeSeason')),
            ],
        ),
    ]
