# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-06 08:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0046_mooringbay_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='preferred_bay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mooringlicensing.MooringBay'),
        ),
    ]
