# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-30 01:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0046_auto_20210330_0901'),
    ]

    operations = [
        migrations.CreateModel(
            name='VesselSizeCategoryGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('vessel_size_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mooringlicensing.VesselSizeCategory')),
            ],
            options={
                'verbose_name_plural': 'Vessel Size Category Group',
            },
        ),
    ]
