# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-30 02:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0050_auto_20210330_0955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vesselsizecategorygroup',
            name='vessel_size_category',
        ),
        migrations.AddField(
            model_name='vesselsizecategory',
            name='vessel_size_category_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vessel_size_categories', to='mooringlicensing.VesselSizeCategoryGroup'),
        ),
    ]
