# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-01 02:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0041_proposal_individual_owner'),
        ('mooringlicensing', '0051_auto_20210330_1023'),
    ]

    operations = [
    ]
