# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-01 03:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0054_auto_20210401_1057'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feeperiod',
            options={'ordering': ['start_date']},
        ),
        migrations.AlterModelOptions(
            name='feeseason',
            options={'verbose_name': 'season'},
        ),
        migrations.AlterField(
            model_name='feeperiod',
            name='fee_season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_periods', to='mooringlicensing.FeeSeason'),
        ),
    ]
