# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-06 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0057_merge_20210406_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeconstructor',
            name='incur_gst',
            field=models.BooleanField(default=True),
        ),
    ]
