# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-06 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0058_feeconstructor_incur_gst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationtype',
            name='code',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
