# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-06 07:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0044_mooringbay_mooring_bay_id'),
        ('mooringlicensing', '0059_auto_20210406_1504'),
    ]

    operations = [
    ]
