# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-08 01:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0062_auto_20210407_0757'),
        ('mooringlicensing', '0063_auto_20210407_1652'),
    ]

    operations = [
    ]
