# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-08 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0064_merge_20210408_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeconstructor',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
