# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-08 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0065_proposal_bay_preferences_numbered'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='mooring_site_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='site_licensee_email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
