# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-08 07:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0066_auto_20210408_1434'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feeconstructor',
            unique_together=set([]),
        ),
    ]
