# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-12 01:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0067_proposal_mooring_authorisation_preference'),
        ('mooringlicensing', '0069_applicationfee_fee_constructor'),
    ]

    operations = [
    ]
