# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-12 05:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0070_merge_20210412_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='preferred_bay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mooringlicensing.MooringBay'),
        ),
    ]
