# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-15 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0078_auto_20210415_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='dcvpermit',
            name='lodgement_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
