# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-15 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0083_auto_20210415_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dcvorganisation',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
