# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-19 03:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0091_merge_20210419_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vesselsizecategory',
            name='start_size',
            field=models.DecimalField(decimal_places=2, default='0.00', help_text='unit [m]', max_digits=8),
        ),
    ]
