# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-23 03:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0098_admissiontype_agegroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeitem',
            name='admission_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mooringlicensing.AdmissionType'),
        ),
        migrations.AddField(
            model_name='feeitem',
            name='age_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mooringlicensing.AgeGroup'),
        ),
    ]
