# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-27 04:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0105_auto_20210423_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dcvadmissionarrival',
            name='dcv_admission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dcv_admission_arrivals', to='mooringlicensing.DcvAdmission'),
        ),
        migrations.AlterField(
            model_name='dcvadmissionarrival',
            name='fee_constructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dcv_admission_arrivals', to='mooringlicensing.FeeConstructor'),
        ),
    ]
