# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-19 05:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0118_mooring'),
    ]

    operations = [
        migrations.AddField(
            model_name='mooring',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
