# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-25 06:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0124_merge_20210525_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='mooring_site_id',
        ),
        migrations.AddField(
            model_name='proposal',
            name='mooring',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mooringlicensing.Mooring'),
        ),
    ]
