# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-02 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0132_waitinglistofferdocument'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='waitinglistofferdocument',
            options={'verbose_name': 'Waiting List Offer Documents'},
        ),
        migrations.AddField(
            model_name='waitinglistofferdocument',
            name='can_hide',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='waitinglistofferdocument',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='waitinglistofferdocument',
            name='input_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='waitinglistofferdocument',
            name='_file',
            field=models.FileField(max_length=512, upload_to=''),
        ),
    ]
