# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-04 06:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0140_auto_20210604_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sticker',
            name='approval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stickers', to='mooringlicensing.Approval'),
        ),
    ]
