# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-08 02:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0142_auto_20210604_1516'),
        ('mooringlicensing', '0138_mooring_mooring_licence'),
    ]

    operations = [
    ]
