# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-08 04:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0143_merge_20210608_1038'),
        ('mooringlicensing', '0144_auto_20210604_1622'),
    ]

    operations = [
    ]
