# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-10 09:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0148_auto_20210609_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mooringonapproval',
            name='description',
        ),
        migrations.RemoveField(
            model_name='mooringonapproval',
            name='name',
        ),
        migrations.RemoveField(
            model_name='mooringonapproval',
            name='uploaded_date',
        ),
    ]
