# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-14 00:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0150_auto_20210611_1150'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sticker',
            options={'ordering': ['-number']},
        ),
    ]
