# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-16 05:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0155_auto_20210615_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='mooringonapproval',
            name='sticker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mooringlicensing.Sticker'),
        ),
    ]
