# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-21 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0163_remove_authoriseduserpermit_endorsed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='endorser_reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
