# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-22 03:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0167_auto_20210622_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='endorser_reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
