# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-22 06:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0170_merge_20210622_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='vesselonapproval',
            name='approval',
        ),
        migrations.RemoveField(
            model_name='vesselonapproval',
            name='sticker',
        ),
        migrations.RemoveField(
            model_name='vesselonapproval',
            name='vessel',
        ),
        migrations.RemoveField(
            model_name='vesselonapproval',
            name='vessel_ownership',
        ),
        migrations.RemoveField(
            model_name='approval',
            name='vessels',
        ),
        migrations.DeleteModel(
            name='VesselOnApproval',
        ),
        migrations.AddField(
            model_name='approvalhistory',
            name='approval',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mooringlicensing.Approval'),
        ),
        migrations.AddField(
            model_name='approvalhistory',
            name='proposal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_history_records', to='mooringlicensing.Proposal'),
        ),
        migrations.AddField(
            model_name='approvalhistory',
            name='sticker',
            field=models.ManyToManyField(to='mooringlicensing.Sticker'),
        ),
        migrations.AddField(
            model_name='approvalhistory',
            name='vessel_ownership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mooringlicensing.VesselOwnership'),
        ),
    ]
