# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-24 08:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0178_auto_20210624_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='StickerPrintingContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('type', models.CharField(choices=[('to', 'to'), ('cc', 'cc'), ('bcc', 'bcc')], max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='key',
            field=models.CharField(choices=[('dcv_permit_template_file', 'DcvPermit template file'), ('dcv_admission_template_file', 'DcvAdmission template file'), ('approval_template_file', 'Approval template file'), ('reset_waiting_list_allocation_days', 'Reset unclaimed Waiting List Allocations after X days'), ('sticker_printing_contact', 'Contact email addresses for printing the sticker')], max_length=255),
        ),
        migrations.AddField(
            model_name='stickerprintingcontact',
            name='global_setting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mooringlicensing.GlobalSettings'),
        ),
    ]
