# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-07-02 02:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0184_auto_20210630_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='sticker',
            name='vessel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mooringlicensing.Vessel'),
        ),
        migrations.AlterField(
            model_name='sticker',
            name='status',
            field=models.CharField(choices=[('ready', 'Ready'), ('awaiting_printing', 'Awaiting Printing'), ('current', 'Current'), ('to_be_returned', 'To be Returned'), ('returned', 'Returned'), ('lost', 'Lost'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='ready', max_length=40),
        ),
    ]
