# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-07-02 02:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0185_auto_20210702_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sticker',
            name='vessel_details',
        ),
    ]
