# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-07-08 05:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0186_remove_sticker_vessel_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationfee',
            name='fee_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mooringlicensing.FeeItem'),
        ),
        migrations.AddField(
            model_name='dcvadmissionfee',
            name='fee_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mooringlicensing.FeeItem'),
        ),
        migrations.AddField(
            model_name='dcvpermitfee',
            name='fee_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mooringlicensing.FeeItem'),
        ),
    ]
