# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-07-09 07:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0189_auto_20210709_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationfee',
            name='fee_constructor',
        ),
        migrations.RemoveField(
            model_name='applicationfee',
            name='fee_item',
        ),
        migrations.RemoveField(
            model_name='dcvadmissionfee',
            name='fee_item',
        ),
        migrations.RemoveField(
            model_name='dcvpermitfee',
            name='fee_constructor',
        ),
        migrations.RemoveField(
            model_name='dcvpermitfee',
            name='fee_item',
        ),
    ]
