# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-07-20 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0195_auto_20210720_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='internal_status',
            field=models.CharField(blank=True, choices=[('waiting', 'Waiting for offer'), ('offered', 'Mooring Licence offered'), ('submitted', 'Mooring Licence application submitted'), ('expired', 'Mooring Licence application expired'), ('approved', 'Mooring Licence approved'), ('licence_declined', 'Mooring Licence declined')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='approval',
            name='status',
            field=models.CharField(choices=[('current', 'Current'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('surrendered', 'Surrendered'), ('suspended', 'Suspended'), ('fulfilled', 'Fulfilled')], default='current', max_length=40),
        ),
    ]
