# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-08-05 03:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0201_stickerprintingresponse_imported_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='stickerprintingresponse',
            name='email_body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stickerprintingresponse',
            name='email_subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
