# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-08-05 04:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0204_stickerprintingresponse_email_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='stickerprintingresponse',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
