# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-08-16 07:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0207_merge_20210805_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dcvvessel',
            name='uvi_vessel_identifier',
        ),
    ]
