# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-08-17 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0213_stickerprintingresponse_no_errors_when_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='dcvadmissionarrival',
            name='departure_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
