# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-08-18 07:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0210_mooringonapproval_end_date'),
        ('mooringlicensing', '0214_dcvadmissionarrival_departure_date'),
    ]

    operations = [
    ]
