# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-08-18 10:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0211_auto_20210818_1640'),
        ('mooringlicensing', '0215_merge_20210818_1524'),
    ]

    operations = [
    ]
