# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-08-19 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0215_merge_20210818_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='vesselsizecategory',
            name='incremental',
            field=models.BooleanField(default=False),
        ),
    ]
