# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-08-19 02:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0218_auto_20210819_1045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feeitem',
            name='incremental_amount',
        ),
    ]
