# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-08-23 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0222_auto_20210820_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='OracleCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('value', models.CharField(blank=True, default='T1 EXEMPT', max_length=50, null=True)),
                ('date_of_enforcement', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
