# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-08-23 06:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0223_oraclecode'),
    ]

    operations = [
        migrations.CreateModel(
            name='OracleCodeApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OracleCodeItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, default='T1 EXEMPT', max_length=50, null=True)),
                ('date_of_enforcement', models.DateField(blank=True, null=True)),
                ('oracle_code_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mooringlicensing.OracleCodeApplication')),
            ],
        ),
        migrations.DeleteModel(
            name='OracleCode',
        ),
    ]
