# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-08-23 08:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0225_auto_20210823_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='oraclecodeitem',
            name='application_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oracle_code_items', to='mooringlicensing.ApplicationType'),
        ),
    ]
