# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-08-24 08:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0228_stickeractionfee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stickeractionfee',
            name='sticker_action_detail',
        ),
        migrations.AddField(
            model_name='stickeractiondetail',
            name='sticker_action_fee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mooringlicensing.StickerActionFee'),
        ),
    ]
