# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-08-25 03:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0230_merge_20210824_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stickeractiondetail',
            name='sticker_action_fee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sticker_action_details', to='mooringlicensing.StickerActionFee'),
        ),
    ]
