# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-08-25 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0231_auto_20210825_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeItemStickerReplacement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default='0.00', help_text='$', max_digits=8)),
                ('date_of_enforcement', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Fee (sticker replacement)',
            },
        ),
        migrations.AlterModelOptions(
            name='applicationtype',
            options={'verbose_name': 'Oracle code'},
        ),
    ]
