# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-08-25 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0233_feeitemstickerreplacement_enabled'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feeitemstickerreplacement',
            options={'verbose_name': 'Fee (sticker replacement)', 'verbose_name_plural': 'Fee (sticker replacement)'},
        ),
        migrations.AddField(
            model_name='feeitemstickerreplacement',
            name='incur_gst',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='feeitemstickerreplacement',
            name='amount',
            field=models.DecimalField(decimal_places=2, default='0.00', help_text='unit [$AU]', max_digits=8),
        ),
    ]
