# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-09-06 01:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0239_auto_20210903_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeseason',
            name='application_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mooringlicensing.ApplicationType'),
        ),
    ]
