# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-09-07 03:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0243_auto_20210906_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vesselregistrationdocument',
            name='proposal',
        ),
        migrations.AddField(
            model_name='vesselregistrationdocument',
            name='vessel_ownership',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='vessel_registration_documents', to='mooringlicensing.VesselOwnership'),
            preserve_default=False,
        ),
    ]
