# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-09-08 01:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0245_proposal_temporary_document_collection_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvaluseraction',
            name='who',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
