# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-09-13 01:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0248_auto_20210912_1243'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approvalhistory',
            options={'ordering': ['-id']},
        ),
    ]
