# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-09-14 03:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0252_auto_20210914_1133'),
        ('mooringlicensing', '0252_dcvpermit_migrated'),
    ]

    operations = [
    ]
