# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-09-17 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0255_auto_20210914_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='export_to_mooring_booking',
            field=models.BooleanField(default=False),
        ),
    ]
