# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-09-20 04:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0259_remove_approval_fee_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='sticker',
            name='fee_season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mooringlicensing.FeeSeason'),
        ),
    ]
