# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-10-11 02:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0261_auto_20210928_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='VesselOwnershipOnApproval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_date', models.DateField(blank=True, null=True)),
                ('approval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mooringlicensing.Approval')),
                ('sticker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mooringlicensing.Sticker')),
                ('vessel_ownership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mooringlicensing.VesselOwnership')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='vesselownershiponapproval',
            unique_together=set([('vessel_ownership', 'approval')]),
        ),
    ]
