# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-10-12 07:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0262_auto_20211011_1039'),
        ('mooringlicensing', '0267_auto_20211007_1204'),
    ]

    operations = [
    ]
