# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-10-18 03:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0269_auto_20211012_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='assigned_assessor',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='proposalrequest_ptr',
        ),
        migrations.AlterUniqueTogether(
            name='proposalassessment',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='proposalassessment',
            name='proposal',
        ),
        migrations.RemoveField(
            model_name='proposalassessment',
            name='submitter',
        ),
        migrations.RemoveField(
            model_name='proposalassessmentanswer',
            name='assessment',
        ),
        migrations.RemoveField(
            model_name='proposalassessmentanswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='proposalonhold',
            name='documents',
        ),
        migrations.RemoveField(
            model_name='proposalonhold',
            name='officer',
        ),
        migrations.RemoveField(
            model_name='proposalonhold',
            name='proposal',
        ),
        migrations.DeleteModel(
            name='Assessment',
        ),
        migrations.DeleteModel(
            name='ChecklistQuestion',
        ),
        migrations.DeleteModel(
            name='ProposalAssessment',
        ),
        migrations.DeleteModel(
            name='ProposalAssessmentAnswer',
        ),
        migrations.DeleteModel(
            name='ProposalOnHold',
        ),
    ]
