# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-10-18 05:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0270_auto_20211018_1145'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
