# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-10-21 01:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0272_auto_20211020_1408'),
        ('mooringlicensing', '0273_merge_20211019_1218'),
    ]

    operations = [
    ]
