# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-05 05:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0275_compliance_submitter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amendmentrequest',
            name='reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mooringlicensing.AmendmentReason'),
        ),
        migrations.AlterField(
            model_name='companyownership',
            name='blocking_proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mooringlicensing.Proposal'),
        ),
        migrations.AlterField(
            model_name='mooring',
            name='mooring_licence',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mooring', to='mooringlicensing.MooringLicence'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='approval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mooringlicensing.Approval'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='approval_level_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_level_document', to='mooringlicensing.ProposalDocument'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='org_applicant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_applications', to='mooringlicensing.Organisation'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='previous_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='succeeding_proposals', to='mooringlicensing.Proposal'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='proposal_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mooringlicensing.ProposalType'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='proxy_applicant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mooringlicensing_proxy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='submitter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mooringlicensing_proposals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='vessel_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mooringlicensing.VesselDetails'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='vessel_ownership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mooringlicensing.VesselOwnership'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='waiting_list_allocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ria_generated_proposal', to='mooringlicensing.Approval'),
        ),
        migrations.AlterField(
            model_name='proposaldeclineddetails',
            name='officer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proposaldeclineddetails',
            name='proposal',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mooringlicensing.Proposal'),
        ),
        migrations.AlterField(
            model_name='proposalrequest',
            name='officer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proposalrequirement',
            name='standard_requirement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mooringlicensing.ProposalStandardRequirement'),
        ),
        migrations.AlterField(
            model_name='proposaluseraction',
            name='who',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stickerprintingresponse',
            name='sticker_printing_response_email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mooringlicensing.StickerPrintingResponseEmail'),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='blocking_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocked_vessel', to='mooringlicensing.VesselOwnership'),
        ),
    ]
