# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-03-14 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0277_proposal_fee_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='keep_existing_vessel',
            field=models.BooleanField(default=True),
        ),
    ]
