# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-03-16 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0278_proposal_keep_existing_vessel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='keep_existing_mooring',
            field=models.BooleanField(default=True),
        ),
    ]
