# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-03-16 00:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0279_remove_sticker_replaced_for_renewal'),
    ]

    operations = [
        migrations.AddField(
            model_name='sticker',
            name='sticker_to_replace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mooringlicensing.Sticker'),
        ),
    ]
