# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-03-16 02:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0281_merge_20220316_0934'),
        ('mooringlicensing', '0279_auto_20220316_0840'),
    ]

    operations = [
    ]
