# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-03-16 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0282_merge_20220316_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalhistory',
            name='reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
