# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-03-28 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0285_auto_20220328_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='listed_moorings',
            field=models.ManyToManyField(related_name='listed_on_proposals', to='mooringlicensing.Mooring'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='listed_vessels',
            field=models.ManyToManyField(related_name='listed_on_proposals', to='mooringlicensing.VesselOwnership'),
        ),
    ]
