# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-04-27 05:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0289_auto_20220411_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='waiting_list_allocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ria_generated_proposal', to='mooringlicensing.WaitingListAllocation'),
        ),
    ]
