# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-05-12 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0291_merge_20220503_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationfee',
            name='system_invoice',
            field=models.BooleanField(default=False),
        ),
    ]
