# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-05-19 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0294_feeitemapplicationfee_amount_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeitemapplicationfee',
            name='amount_to_be_paid',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=8, null=True),
        ),
    ]
