# Generated by Django 5.1.8 on 2025-05-08 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_cmd', models.CharField(blank=True, max_length=1000, null=True)),
                ('system_id', models.CharField(blank=True, max_length=4, null=True)),
                ('status', models.SmallIntegerField(choices=[(0, 'Pending'), (1, 'Running'), (2, 'Completed'), (3, 'Failed')], default=0)),
                ('parameters_json', models.TextField(blank=True, null=True)),
                ('processed_dt', models.DateTimeField(blank=True, default=None, null=True)),
                ('user', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
