# Generated by Django 5.1.8 on 2025-05-09 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobqueue',
            name='parameters_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
