# Generated by Django 5.2.4 on 2025-09-01 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='page',
            field=models.TextField(blank=True, choices=[('', 'Dashboard'), ('proposal', 'Proposal')], default='', null=True),
        ),
    ]
