# Generated by Django 5.2.4 on 2025-09-02 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_notice_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='page',
            field=models.TextField(blank=True, choices=[('', 'External Dashboard'), ('proposal', 'Application Page'), ('compliance', 'Compliance Page')], default='', null=True),
        ),
    ]
