# Generated by Django 5.2.4 on 2025-09-04 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_notice_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='page',
            field=models.TextField(blank=True, choices=[('External Dashboard', 'External Dashboard'), ('Application Page', 'Application Page'), ('Compliance Page', 'Compliance Page')], default='External Dashboard', null=True),
        ),
    ]
