# Generated by Django 3.2.16 on 2023-01-18 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0002_applicationfee_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeCalculation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=36, null=True)),
                ('data', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
