# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-09 03:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0003_auto_20210309_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='application_type',
        ),
        migrations.AlterField(
            model_name='proposal',
            name='proposal_type',
            field=models.CharField(choices=[('new_proposal', 'New Application'), ('amendment', 'Amendment'), ('renewal', 'Renewal'), ('external', 'External')], default='new_proposal', max_length=40, verbose_name='Proposal Status Type'),
        ),
    ]
