# Generated by Django 3.2.16 on 2023-02-03 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0003_feecalculation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complianceuseraction',
            name='who',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mooringuseraction',
            name='who',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organisationaction',
            name='who',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organisationrequestuseraction',
            name='who',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
