# Generated by Django 3.2.16 on 2023-02-07 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0004_auto_20230203_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='dcvadmission',
            name='uuid',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='dcvpermit',
            name='uuid',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
