# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-09 04:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0004_auto_20210309_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waitinglistapplication',
            name='proposal_ptr',
        ),
        migrations.DeleteModel(
            name='WaitingListApplication',
        ),
    ]
