# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-09 06:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0002_auto_20210302_1631'),
        ('mooringlicensing', '0004_auto_20210309_1157'),
    ]

    operations = [
    ]
