# Generated by Django 3.2.16 on 2023-02-07 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0005_auto_20230207_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dcvadmission',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='dcvpermit',
            name='uuid',
        ),
    ]
