# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-09 06:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0005_auto_20210309_1241'),
        ('mooringlicensing', '0005_merge_20210309_1424'),
    ]

    operations = [
    ]
