# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-09 06:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0006_merge_20210309_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitingListApplication',
            fields=[
                ('proposal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mooringlicensing.Proposal')),
            ],
            bases=('mooringlicensing.proposal',),
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='previous_application',
        ),
    ]
