# Generated by Django 3.2.16 on 2023-02-09 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0007_auto_20230207_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='stickeractionfee',
            name='uuid',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
