# Generated by Django 3.2.16 on 2023-02-10 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0009_emailuserlogentry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailUserLogEntry',
        ),
    ]
