# Generated by Django 3.2.16 on 2023-02-10 06:01

from django.db import migrations, models
import django.db.models.deletion
import mooringlicensing.components.main.models
import mooringlicensing.components.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0011_emailuserlogentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailUserLogDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('_file', models.FileField(upload_to=mooringlicensing.components.users.models.update_emailuser_comms_log_filename)),
                ('log_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='mooringlicensing.emailuserlogentry')),
            ],
        ),
    ]
