# Generated by Django 3.2.16 on 2023-02-16 06:06

from django.db import migrations, models
import mooringlicensing.components.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0012_emailuserlogdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailuserlogdocument',
            name='_file',
            field=models.FileField(max_length=300, upload_to=mooringlicensing.components.users.models.update_emailuser_comms_log_filename),
        ),
    ]
