# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-12 06:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0013_waitinglistallocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualAdmissionPermit',
            fields=[
                ('approval', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mooringlicensing.Approval')),
            ],
            bases=('mooringlicensing.approval',),
        ),
        migrations.CreateModel(
            name='AuthorisedUserPermit',
            fields=[
                ('approval', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mooringlicensing.Approval')),
            ],
            bases=('mooringlicensing.approval',),
        ),
        migrations.CreateModel(
            name='MooringLicence',
            fields=[
                ('approval', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mooringlicensing.Approval')),
            ],
            bases=('mooringlicensing.approval',),
        ),
    ]
