# Generated by Django 3.2.16 on 2023-02-16 06:20

from django.db import migrations, models
import mooringlicensing.components.approvals.models
import mooringlicensing.components.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0013_alter_emailuserlogdocument__file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailuserlogdocument',
            name='_file',
            field=models.FileField(max_length=512, upload_to=mooringlicensing.components.users.models.update_emailuser_comms_log_filename),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='_file',
            field=models.FileField(blank=True, max_length=512, null=True, upload_to='approval_permit_template'),
        ),
        migrations.AlterField(
            model_name='renewaldocument',
            name='_file',
            field=models.FileField(max_length=512, upload_to=mooringlicensing.components.approvals.models.update_approval_doc_filename),
        ),
    ]
