# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-16 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0014_annualadmissionpermit_authoriseduserpermit_mooringlicence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='customer_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('with_assessor', 'Under Review'), ('amendment_required', 'Amendment Required'), ('approved', 'Approved'), ('declined', 'Declined'), ('discarded', 'Discarded'), ('awaiting_payment', 'Awaiting Payment')], default='with_assessor', max_length=40, verbose_name='Customer Status'),
        ),
    ]
