# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-15 08:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mooringlicensing', '0014_annualadmissionpermit_authoriseduserpermit_mooringlicence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(blank=True, max_length=200)),
                ('emailuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Owners',
            },
        ),
        migrations.CreateModel(
            name='Vessel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rego_no', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Vessels',
            },
        ),
        migrations.CreateModel(
            name='VesselDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vessel_name', models.CharField(max_length=400)),
                ('vessel_size', models.DecimalField(decimal_places=2, default='0.00', max_digits=8)),
                ('vessel_draft', models.DecimalField(decimal_places=2, default='0.00', max_digits=8)),
                ('vessel_beam', models.DecimalField(decimal_places=2, default='0.00', max_digits=8)),
                ('vessel_weight', models.DecimalField(decimal_places=2, default='0.00', max_digits=8)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=50)),
                ('exported', models.BooleanField(default=False)),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mooringlicensing.Vessel')),
            ],
            options={
                'verbose_name_plural': 'Vessel Details',
            },
        ),
        migrations.CreateModel(
            name='VesselDetailsOwnership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('editable', models.BooleanField(default=False)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mooringlicensing.Owner')),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mooringlicensing.Vessel')),
            ],
            options={
                'verbose_name_plural': 'Vessel Details Ownership',
            },
        ),
        migrations.RemoveField(
            model_name='vesselrelations',
            name='proposal_id',
        ),
        migrations.RemoveField(
            model_name='vesselrelations',
            name='vessel_id',
        ),
        migrations.AddField(
            model_name='approval',
            name='exported',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='VesselDetail',
        ),
        migrations.DeleteModel(
            name='VesselRelations',
        ),
        migrations.AddField(
            model_name='owner',
            name='vessels',
            field=models.ManyToManyField(through='mooringlicensing.VesselDetailsOwnership', to='mooringlicensing.Vessel'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='vessel_details',
            field=models.ManyToManyField(to='mooringlicensing.VesselDetails'),
        ),
    ]
