# Generated by Django 3.2.16 on 2023-02-21 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0014_auto_20230216_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='proposal_applicant_details',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
