# Generated by Django 3.2.16 on 2023-02-21 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0015_proposal_proposal_applicant_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposal',
            old_name='proposal_applicant_details',
            new_name='personal_details',
        ),
    ]
