# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-16 02:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0015_auto_20210315_1642'),
        ('mooringlicensing', '0015_auto_20210316_1025'),
    ]

    operations = [
    ]
