# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-22 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0017_auto_20210318_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='vesseldetails',
            name='vessel_type',
            field=models.CharField(choices=[('yacht', 'Yacht'), ('cabin_cruiser', 'Cabin Cruiser'), ('tender', 'Tender'), ('other', 'Other')], default=None, max_length=20),
            preserve_default=False,
        ),
    ]
