# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-23 03:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0019_electoralrolldocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='VesselRegistrationDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('_file', models.FileField(max_length=512, upload_to='')),
                ('input_name', models.CharField(blank=True, max_length=255, null=True)),
                ('can_delete', models.BooleanField(default=True)),
                ('can_hide', models.BooleanField(default=False)),
                ('hidden', models.BooleanField(default=False)),
                ('vesseldetailsownership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='mooringlicensing.VesselDetailsOwnership')),
            ],
            options={
                'verbose_name': 'Vessel Registration Papers',
            },
        ),
        migrations.AlterField(
            model_name='electoralrolldocument',
            name='emailuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electoral_roll_documents', to=settings.AUTH_USER_MODEL),
        ),
    ]
