# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-24 01:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0021_auto_20210323_1152'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VesselDetailsOwnership',
            new_name='VesselOwnership',
        ),
        migrations.RenameField(
            model_name='vesseldetails',
            old_name='vessel_size',
            new_name='vessel_length',
        ),
        migrations.AddField(
            model_name='vesseldetails',
            name='vessel_overall_length',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=8),
        ),
    ]
