# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-24 01:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0022_auto_20210323_1158'),
        ('mooringlicensing', '0022_auto_20210324_0917'),
    ]

    operations = [
    ]
