# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-25 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0028_auto_20210324_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='vessel_details',
        ),
        migrations.AddField(
            model_name='proposal',
            name='vessel_details_many',
            field=models.ManyToManyField(related_name='proposal_vessel_details_many', to='mooringlicensing.VesselDetails'),
        ),
    ]
