# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-25 01:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0030_proposal_vessel_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='vessel_details_many',
        ),
    ]
