# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-26 06:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0035_auto_20210326_1434'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vesselownership',
            unique_together=set([('owner', 'vessel', 'org_name')]),
        ),
    ]
