# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-26 08:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0030_applicationfee_invoice_reference'),
        ('mooringlicensing', '0036_auto_20210326_1445'),
    ]

    operations = [
    ]
