# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-30 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0040_proposal_vessel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='individual_owner',
            field=models.NullBooleanField(),
        ),
    ]
