# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-01 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0041_proposal_individual_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='insurance_choice',
            field=models.CharField(blank=True, choices=[('five_million', '$5 million Third Party Liability insurance cover - required for vessels of length less than 6.4 metres'), ('ten_million', '$10 million Third Party Liability insurance cover - required for vessels of length 6.4 metres or greater'), ('over_ten', 'over $10 million')], max_length=20),
        ),
    ]
