# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-29 08:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0042_auto_20210329_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeePeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeeSeason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='feeperiod',
            name='fee_season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mooringlicensing.FeeSeason'),
        ),
    ]
