# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-06 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0043_mooringbay'),
    ]

    operations = [
        migrations.AddField(
            model_name='mooringbay',
            name='mooring_bay_id',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
