# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-30 00:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0044_feeseasonapplicationtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feeseasonapplicationtype',
            name='application_type',
        ),
        migrations.RemoveField(
            model_name='feeseasonapplicationtype',
            name='fee_season',
        ),
        migrations.DeleteModel(
            name='FeeSeasonApplicationType',
        ),
    ]
