# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-06 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0045_auto_20210406_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='mooringbay',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
