# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-30 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0045_auto_20210330_0853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vesselsizecategory',
            name='end_size',
        ),
        migrations.RemoveField(
            model_name='vesselsizecategory',
            name='status',
        ),
        migrations.AddField(
            model_name='vesselsizecategory',
            name='include_start_size',
            field=models.BooleanField(default=True),
        ),
    ]
