# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-01 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0055_auto_20210401_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeseason',
            name='name',
            field=models.CharField(default='---', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vesselsizecategorygroup',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
