# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-06 06:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0056_auto_20210401_1550'),
        ('mooringlicensing', '0042_proposal_insurance_choice'),
    ]

    operations = [
    ]
