# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-06 09:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0047_proposal_preferred_bay'),
        ('mooringlicensing', '0060_merge_20210406_1554'),
    ]

    operations = [
    ]
