# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-06 23:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0061_merge_20210407_0757'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approval',
            options={'ordering': ['-id']},
        ),
    ]
