# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-07 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0061_merge_20210406_1707'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approval',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='proposal',
            name='silent_elector',
            field=models.NullBooleanField(),
        ),
    ]
