# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-07 08:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0062_auto_20210407_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electoralrolldocument',
            name='emailuser',
        ),
        migrations.AddField(
            model_name='electoralrolldocument',
            name='proposal',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='electoral_roll_documents', to='mooringlicensing.Proposal'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='electoralrolldocument',
            name='_file',
            field=models.FileField(max_length=512, upload_to=''),
        ),
    ]
