# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-08 06:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0065_feeconstructor_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeconstructor',
            name='application_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mooringlicensing.ApplicationType'),
        ),
        migrations.AlterField(
            model_name='feeconstructor',
            name='fee_season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mooringlicensing.FeeSeason'),
        ),
        migrations.AlterField(
            model_name='feeconstructor',
            name='vessel_size_category_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mooringlicensing.VesselSizeCategoryGroup'),
        ),
    ]
