# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-09 00:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0066_auto_20210408_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='mooring_authorisation_preference',
            field=models.CharField(blank=True, choices=[('site_licensee', 'By a mooring site licensee for their mooring'), ('ria', 'By Rottnest Island Authority for a mooring allocated by the Authority')], max_length=20),
        ),
    ]
