# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-09 00:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0067_auto_20210408_1521'),
        ('mooringlicensing', '0065_proposal_bay_preferences_numbered'),
    ]

    operations = [
    ]
