# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-12 03:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0070_auto_20210409_1643'),
        ('mooringlicensing', '0070_merge_20210412_0946'),
    ]

    operations = [
    ]
