# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-13 07:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0070_auto_20210409_1643'),
        ('mooringlicensing', '0071_auto_20210412_1341'),
    ]

    operations = [
    ]
