# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-14 00:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0072_dcvorganisation_dcvpermit_dcvpermitdocument_dcvvessel'),
        ('mooringlicensing', '0072_merge_20210413_1538'),
    ]

    operations = [
    ]
