# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-15 01:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0074_auto_20210414_1026'),
        ('mooringlicensing', '0073_merge_20210414_0829'),
    ]

    operations = [
    ]
