# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-15 06:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0082_applicationtype_oracle_code_application'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicationtype',
            old_name='oracle_code_application',
            new_name='oracle_code',
        ),
    ]
