# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-15 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0084_auto_20210415_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dcvorganisation',
            name='abn',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='ABN'),
        ),
    ]
