# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-16 02:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0086_auto_20210416_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='dcvpermit',
            name='fee_season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mooringlicensing.FeeSeason'),
        ),
    ]
