# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-16 10:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0087_dcvpermit_fee_season'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='percentage',
        ),
    ]
