# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-16 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0087_dcvpermit_fee_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='_file',
            field=models.FileField(blank=True, null=True, upload_to='dcv_permit_template'),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='key',
            field=models.CharField(choices=[('dcv_permit_template_file', 'DcvPermit template file')], max_length=255),
        ),
    ]
