# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-16 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0088_remove_proposal_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='percentage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
