# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-19 02:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0090_auto_20210419_1014'),
        ('mooringlicensing', '0088_auto_20210416_1621'),
    ]

    operations = [
    ]
