# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-22 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0094_dcvadmissionfee'),
    ]

    operations = [
        migrations.AddField(
            model_name='dcvadmission',
            name='lodgement_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
