# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-22 07:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mooringlicensing.components.approvals.models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0095_dcvadmission_lodgement_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='DcvAdmissionDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('_file', models.FileField(max_length=512, upload_to=mooringlicensing.components.approvals.models.update_dcv_admission_doc_filename)),
                ('can_delete', models.BooleanField(default=False)),
                ('dcv_admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='mooringlicensing.DcvAdmission')),
            ],
        ),
    ]
