# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-23 06:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0100_auto_20210423_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='dcvadmission',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dcvadmission',
            name='fee_season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mooringlicensing.FeeSeason'),
        ),
        migrations.AddField(
            model_name='dcvadmission',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feeitem',
            name='amount',
            field=models.DecimalField(decimal_places=2, default='0.00', help_text='$', max_digits=8),
        ),
    ]
