# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-23 07:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0102_dcvadmissionfee_fee_constructor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dcvadmission',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='dcvadmission',
            name='fee_season',
        ),
        migrations.RemoveField(
            model_name='dcvadmission',
            name='start_date',
        ),
    ]
