# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-30 05:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0106_auto_20210427_1247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dcvvessel',
            old_name='uiv_vessel_identifier',
            new_name='uvi_vessel_identifier',
        ),
    ]
