# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-30 06:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0107_auto_20210430_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dcvpermit',
            name='dcv_vessel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dcv_permits', to='mooringlicensing.DcvVessel'),
        ),
        migrations.AlterField(
            model_name='dcvpermit',
            name='fee_season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dcv_permits', to='mooringlicensing.FeeSeason'),
        ),
        migrations.AlterField(
            model_name='dcvpermit',
            name='submitter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dcv_permits', to=settings.AUTH_USER_MODEL),
        ),
    ]
