# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-03 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0108_auto_20210430_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='dcvadmission',
            name='contact_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dcvadmission',
            name='skipper',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
