# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-03 05:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0109_auto_20210503_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='dcvadmission',
            name='dcv_vessel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dcv_admissions', to='mooringlicensing.DcvVessel'),
        ),
    ]
