# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-10 07:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0110_dcvadmission_dcv_vessel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='CompanyOwnership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('draft', 'Draft'), ('old', 'Old'), ('declined', 'Declined')], default='draft', max_length=50)),
                ('percentage', models.IntegerField(blank=True, null=True)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('blocking_proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mooringlicensing.Proposal')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mooringlicensing.Company')),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mooringlicensing.Vessel')),
            ],
            options={
                'verbose_name_plural': 'Company Ownership',
            },
        ),
        migrations.RemoveField(
            model_name='vesseldetails',
            name='blocking_proposal',
        ),
        migrations.RemoveField(
            model_name='vesseldetails',
            name='status',
        ),
        migrations.AddField(
            model_name='vesselownership',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='vesselownership',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='vesselownership',
            unique_together=set([]),
        ),
        migrations.AddField(
            model_name='company',
            name='vessels',
            field=models.ManyToManyField(through='mooringlicensing.CompanyOwnership', to='mooringlicensing.Vessel'),
        ),
        migrations.RemoveField(
            model_name='vesselownership',
            name='org_name',
        ),
        migrations.AddField(
            model_name='vesselownership',
            name='company_ownership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mooringlicensing.CompanyOwnership'),
        ),
    ]
