# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-11 04:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0111_auto_20210510_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='org_name',
        ),
        migrations.AddField(
            model_name='proposal',
            name='company_ownership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mooringlicensing.CompanyOwnership'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
