# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-17 01:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0114_auto_20210512_1027'),
        ('mooringlicensing', '0111_proposalstandardrequirement_application_type'),
    ]

    operations = [
    ]
