# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-19 05:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0117_auto_20210519_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mooring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('vessel_size_limit', models.DecimalField(decimal_places=2, default='0.00', max_digits=8)),
                ('vessel_draft_limit', models.DecimalField(decimal_places=2, default='0.00', max_digits=8)),
                ('vessel_beam_limit', models.DecimalField(decimal_places=2, default='0.00', max_digits=8)),
                ('vessel_weight_limit', models.DecimalField(decimal_places=2, default='0.00', max_digits=8)),
                ('mooring_bookings_id', models.IntegerField()),
                ('mooring_bookings_mooring_specification', models.IntegerField()),
                ('mooring_bookings_bay_id', models.IntegerField()),
                ('mooring_bay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mooringlicensing.MooringBay')),
            ],
            options={
                'verbose_name_plural': 'Moorings',
            },
        ),
    ]
