# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-21 01:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0117_auto_20210521_0924'),
        ('mooringlicensing', '0119_mooring_active'),
    ]

    operations = [
    ]
