# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-24 08:24
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0120_merge_20210521_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='authoriseduserapplication',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
