# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-24 02:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0121_auto_20210521_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='vessel',
            name='blocking_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocked_vessel', to='mooringlicensing.VesselOwnership'),
        ),
    ]
