# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-25 03:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0123_auto_20210524_1145'),
        ('mooringlicensing', '0121_authoriseduserapplication_uuid'),
    ]

    operations = [
    ]
