# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-25 06:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0124_merge_20210525_0959'),
        ('mooringlicensing', '0125_auto_20210525_1417'),
    ]

    operations = [
    ]
