# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-31 09:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0128_mooringreportdocument_writtenproofdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='ria_selected_mooring',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mooringlicensing.Mooring'),
        ),
        migrations.AddField(
            model_name='approval',
            name='ria_selected_mooring_bay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mooringlicensing.MooringBay'),
        ),
    ]
