# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-02 02:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0130_approval_wla_queue_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='wla_order',
            field=models.PositiveIntegerField(help_text='wla order per mooring bay', null=True),
        ),
    ]
