# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-03 03:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0130_auto_20210602_1145'),
        ('mooringlicensing', '0135_proposal_waiting_list_allocation'),
    ]

    operations = [
    ]
