# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-04 02:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0136_merge_20210603_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sticker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, default='', max_length=9)),
                ('status', models.CharField(choices=[('current', 'Current'), ('new_sticker_requested', 'New Sticker Requested'), ('awaiting_sticker', 'Awaiting Sticker'), ('sticker_returned', 'Sticker Returned'), ('sticker_lost', 'Sticker Lost'), ('expired', 'Expired')], default='awaiting_sticker', max_length=40)),
                ('stickers_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mooringlicensing.StickersDocument')),
            ],
        ),
        migrations.AlterField(
            model_name='approval',
            name='status',
            field=models.CharField(choices=[('current', 'Current'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('surrendered', 'Surrendered'), ('suspended', 'Suspended'), ('extended', 'Extended'), ('awaiting_payment', 'Awaiting Payment'), ('offered', 'Mooring Licence offered')], default='current', max_length=40),
        ),
    ]
