# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-04 03:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0136_auto_20210603_1124'),
        ('mooringlicensing', '0137_auto_20210604_1006'),
    ]

    operations = [
    ]
