# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-08 02:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0137_auto_20210603_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='mooring',
            name='mooring_licence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mooringlicensing.MooringLicence'),
        ),
    ]
