# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-04 03:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0138_merge_20210604_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annualadmissionapplication',
            name='stickers_document',
        ),
        migrations.RemoveField(
            model_name='authoriseduserapplication',
            name='stickers_document',
        ),
        migrations.RemoveField(
            model_name='mooringlicenceapplication',
            name='stickers_document',
        ),
        migrations.AddField(
            model_name='sticker',
            name='approval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mooringlicensing.Approval'),
        ),
    ]
