# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-04 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0141_auto_20210604_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sticker',
            name='number',
            field=models.CharField(blank=True, default='', max_length=9, unique=True),
        ),
        migrations.AlterField(
            model_name='sticker',
            name='status',
            field=models.CharField(choices=[('awaiting_exported', 'Awaiting Exported'), ('awaiting_printed', 'Awaiting Printed'), ('current', 'Current'), ('new_sticker_requested', 'New Sticker Requested'), ('awaiting_sticker', 'Awaiting Sticker'), ('sticker_returned', 'Sticker Returned'), ('sticker_lost', 'Sticker Lost'), ('expired', 'Expired')], default='awaiting_exported', max_length=40),
        ),
    ]
