# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-04 08:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mooringlicensing.components.proposals.models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0142_auto_20210604_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='StickerPrintingResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('_file', models.FileField(max_length=512, upload_to=mooringlicensing.components.proposals.models.update_sticker_response_doc_filename)),
                ('received_datetime', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='sticker',
            name='mailing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sticker',
            name='printing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sticker',
            name='sticker_printing_response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mooringlicensing.StickerPrintingResponse'),
        ),
    ]
