# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-09 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0147_mooringuseraction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalsettings',
            name='key',
            field=models.CharField(choices=[('dcv_permit_template_file', 'DcvPermit template file'), ('dcv_admission_template_file', 'DcvAdmission template file'), ('approval_template_file', 'Approval template file'), ('reset_waiting_list_allocation_days', 'Reset unclaimed Waiting List Allocations after X days')], max_length=255),
        ),
    ]
