# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-14 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0152_stickeractiondetail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stickeractiondetail',
            options={'ordering': ['-date_created']},
        ),
        migrations.AddField(
            model_name='stickeractiondetail',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='stickeractiondetail',
            name='date_of_lost_sticker',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stickeractiondetail',
            name='date_of_return_sticker',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stickeractiondetail',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
