# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-14 07:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0153_auto_20210614_1435'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stickeractiondetail',
            old_name='date_of_return_sticker',
            new_name='date_of_returned_sticker',
        ),
    ]
