# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-17 00:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0156_mooringonapproval_sticker'),
        ('mooringlicensing', '0156_proposal_dot_name'),
    ]

    operations = [
    ]
