# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-17 01:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0157_merge_20210617_0859'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberOfDaysSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('date_of_enforcement', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NumberOfDaysType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, verbose_name='description')),
            ],
        ),
        migrations.AddField(
            model_name='numberofdayssetting',
            name='number_of_days_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mooringlicensing.NumberOfDaysType'),
        ),
    ]
