# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-17 06:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0157_merge_20210617_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='VesselOnApproval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mooringlicensing.Approval')),
                ('sticker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mooringlicensing.Sticker')),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mooringlicensing.Vessel')),
            ],
        ),
        migrations.AddField(
            model_name='approval',
            name='vessels',
            field=models.ManyToManyField(through='mooringlicensing.VesselOnApproval', to='mooringlicensing.Vessel'),
        ),
    ]
