# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-17 07:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0158_auto_20210617_0920'),
        ('mooringlicensing', '0158_auto_20210617_1413'),
    ]

    operations = [
    ]
