# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-22 02:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0160_auto_20210621_1115'),
        ('mooringlicensing', '0164_proposal_endorser_reminder_sent'),
    ]

    operations = [
    ]
