# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-22 03:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0168_auto_20210622_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='date_invited',
            field=models.DateField(blank=True, null=True),
        ),
    ]
