# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-22 06:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0169_proposal_date_invited'),
        ('mooringlicensing', '0161_vesselonapproval_dot_name'),
    ]

    operations = [
    ]
