# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-22 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0169_proposal_date_invited'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='invitee_reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
