# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-22 07:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0173_auto_20210622_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='previous_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='succeeding_proposals', to='mooringlicensing.Proposal'),
        ),
    ]
