# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-22 07:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0170_proposal_invitee_reminder_sent'),
        ('mooringlicensing', '0174_auto_20210622_1503'),
    ]

    operations = [
    ]
