# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-24 08:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0179_auto_20210624_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stickerprintingcontact',
            name='global_setting',
        ),
    ]
