# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-24 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0180_remove_stickerprintingcontact_global_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='stickerprintingcontact',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='stickerprintingcontact',
            name='type',
            field=models.CharField(choices=[('to', 'To'), ('cc', 'Cc'), ('bcc', 'Bcc')], max_length=255),
        ),
    ]
