# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-25 07:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0181_auto_20210624_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='sticker',
            name='vessel_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mooringlicensing.VesselDetails'),
        ),
    ]
