# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-29 03:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0182_sticker_vessel_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='sticker',
            name='fee_constructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mooringlicensing.FeeConstructor'),
        ),
        migrations.AlterField(
            model_name='sticker',
            name='status',
            field=models.CharField(choices=[('printing', 'Printing'), ('current', 'Current'), ('to_be_returned', 'To be Returned'), ('returned', 'Returned'), ('lost', 'Lost'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='printing', max_length=40),
        ),
    ]
