# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-07-09 00:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0187_auto_20210708_1355'),
        ('mooringlicensing', '0187_auto_20210705_1252'),
    ]

    operations = [
    ]
