# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-07-09 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0188_merge_20210709_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationfee',
            name='fee_items',
            field=models.ManyToManyField(related_name='application_fees', to='mooringlicensing.FeeItem'),
        ),
        migrations.AddField(
            model_name='dcvadmissionfee',
            name='fee_items',
            field=models.ManyToManyField(related_name='dcv_admission_fees', to='mooringlicensing.FeeItem'),
        ),
        migrations.AddField(
            model_name='dcvpermitfee',
            name='fee_items',
            field=models.ManyToManyField(related_name='dcv_permit_fees', to='mooringlicensing.FeeItem'),
        ),
    ]
