# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-07-14 01:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0190_auto_20210709_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='vesselsizecategory',
            name='null_vessel',
            field=models.BooleanField(default=False),
        ),
    ]
