# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-07-19 02:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0193_auto_20210716_1609'),
        ('mooringlicensing', '0193_auto_20210719_0906'),
    ]

    operations = [
    ]
