# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-07-22 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0196_auto_20210720_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='internal_status',
            field=models.CharField(blank=True, choices=[('waiting', 'Waiting for offer'), ('offered', 'Mooring Licence offered'), ('submitted', 'Mooring Licence application submitted')], max_length=40, null=True),
        ),
    ]
