# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-07-30 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0197_auto_20210722_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='processing_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('with_assessor', 'With Assessor'), ('with_assessor_requirements', 'With Assessor (Requirements)'), ('with_approver', 'With Approver'), ('printing_sticker', 'Printing Sticker'), ('awaiting_endorsement', 'Awaiting Endorsement'), ('awaiting_documents', 'Awaiting Documents'), ('approved', 'Approved'), ('declined', 'Declined'), ('discarded', 'Discarded'), ('awaiting_payment', 'Awaiting Payment'), ('awaiting_payment_sticker_returned', 'Awaiting Payment and Sticker Returned'), ('awaiting_sticker_returned', 'Awaiting Sticker Returned'), ('expired', 'Expired')], default='with_assessor', max_length=40, verbose_name='Processing Status'),
        ),
    ]
