# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-08-02 02:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0198_auto_20210730_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalhistory',
            name='approval_letter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mooringlicensing.ApprovalDocument'),
        ),
        migrations.AddField(
            model_name='approvalhistory',
            name='reason',
            field=models.CharField(choices=[('new', 'New'), ('replacement_sticker', 'Replacement sticker'), ('vessel_change', 'Vessel added/removed'), ('new_mooring', 'New mooring'), ('mooring_swap', 'Mooring swap')], default='new', max_length=40),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='processing_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('with_assessor', 'With Assessor'), ('with_assessor_requirements', 'With Assessor (Requirements)'), ('with_approver', 'With Approver'), ('printing_sticker', 'Printing Sticker'), ('awaiting_endorsement', 'Awaiting Endorsement'), ('awaiting_documents', 'Awaiting Documents'), ('approved', 'Approved'), ('declined', 'Declined'), ('discarded', 'Discarded'), ('awaiting_payment', 'Awaiting Payment'), ('awaiting_payment_sticker_returned', 'Awaiting Payment and Sticker Returned'), ('awaiting_sticker_returned', 'Awaiting Sticker Returned'), ('expired', 'Expired')], default='draft', max_length=40, verbose_name='Processing Status'),
        ),
    ]
