# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-08-02 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0199_auto_20210802_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalhistory',
            name='reason',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('replacement_sticker', 'Replacement sticker'), ('vessel_add', 'Vessel added'), ('vessel_sold', 'Vessel sold'), ('mooring_add', 'New mooring'), ('mooring_swap', 'Mooring swap')], max_length=40, null=True),
        ),
    ]
