# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-08-05 02:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0201_auto_20210805_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mooring',
            name='mooring_licence',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mooring', to='mooringlicensing.MooringLicence'),
        ),
    ]
