# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-08-05 09:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0206_stickerprintingresponse_email_message_id'),
        ('mooringlicensing', '0202_auto_20210805_1023'),
    ]

    operations = [
    ]
