# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-08-18 05:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0208_remove_dcvvessel_uvi_vessel_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='vesselownership',
            name='mooring_licence_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
