# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-08-18 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0209_vesselownership_mooring_licence_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='mooringonapproval',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
