# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-08-17 04:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0209_proofofidentitydocument_signedlicenceagreementdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='StickerPrintingResponseEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_subject', models.CharField(blank=True, max_length=255, null=True)),
                ('email_body', models.TextField(blank=True, null=True)),
                ('email_date', models.CharField(blank=True, max_length=255, null=True)),
                ('email_from', models.CharField(blank=True, max_length=255, null=True)),
                ('email_message_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
