# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-08-17 04:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0210_stickerprintingresponseemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='stickerprintingresponse',
            name='sticker_printing_response_email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mooringlicensing.StickerPrintingResponseEmail'),
        ),
    ]
