# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-08-18 08:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0210_mooringonapproval_end_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vesselownership',
            old_name='mooring_licence_expiry_date',
            new_name='mooring_licence_end_date',
        ),
    ]
