# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-08-19 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0216_vesselsizecategory_incremental'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeitem',
            name='absolute_amount',
            field=models.BooleanField(default=True),
        ),
    ]
