# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-08-19 08:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0216_merge_20210818_1800'),
        ('mooringlicensing', '0220_auto_20210819_1109'),
    ]

    operations = [
    ]
