# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-08-20 04:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0221_merge_20210819_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='sticker',
            name='proposal_initiated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mooringlicensing.Proposal'),
        ),
        migrations.AlterField(
            model_name='feeitem',
            name='incremental_amount',
            field=models.BooleanField(default=False, help_text='When ticked, The amount will be the increase in the rate per meter'),
        ),
    ]
