# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-08-24 03:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0221_merge_20210819_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='reissued',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='feeitem',
            name='incremental_amount',
            field=models.BooleanField(default=False, help_text='When ticked, The amount will be the increase in the rate per meter'),
        ),
    ]
