# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-08-23 08:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0226_oraclecodeitem_application_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oraclecodeitem',
            name='oracle_code_application',
        ),
        migrations.DeleteModel(
            name='OracleCodeApplication',
        ),
    ]
