# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-08-24 08:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0229_auto_20210824_1604'),
        ('mooringlicensing', '0222_auto_20210824_1139'),
    ]

    operations = [
    ]
