# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-08-26 00:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0231_auto_20210825_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposaluseraction',
            name='who',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
