# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-08-25 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0232_auto_20210825_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeitemstickerreplacement',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
