# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-08-26 04:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0234_auto_20210825_1653'),
        ('mooringlicensing', '0232_auto_20210826_0843'),
    ]

    operations = [
    ]
