# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-08-31 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0235_merge_20210826_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeitemstickerreplacement',
            name='amount',
            field=models.DecimalField(decimal_places=2, default='0.00', help_text='unit [$AU/Sticker]', max_digits=8),
        ),
    ]
