# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-09-01 23:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0236_auto_20210831_1623'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mooringonapproval',
            unique_together=set([('mooring', 'approval')]),
        ),
    ]
