# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-09-02 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0237_auto_20210902_0740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='dot_name',
        ),
        migrations.AddField(
            model_name='vesselownership',
            name='dot_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
