# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-09-06 03:09
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0241_applicationtype_fee_by_fee_constructor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeconstructor',
            name='fee_season',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='application_type', chained_model_field='application_type', on_delete=django.db.models.deletion.CASCADE, to='mooringlicensing.FeeSeason'),
        ),
    ]
