# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-09-07 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0244_auto_20210907_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='temporary_document_collection_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
