# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-09-08 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0246_auto_20210908_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='keep_existing_mooring',
            field=models.BooleanField(default=False),
        ),
    ]
