# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-09-13 22:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0249_auto_20210913_2311'),
        ('mooringlicensing', '0250_remove_vesseldetails_vessel_overall_length'),
    ]

    operations = [
    ]
