# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-09-14 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0251_merge_20210914_0613'),
    ]

    operations = [
        migrations.AddField(
            model_name='dcvpermit',
            name='migrated',
            field=models.BooleanField(default=False),
        ),
    ]
