# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-09-14 07:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0253_merge_20210914_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='vessel_overall_length',
        ),
    ]
