# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-09-20 03:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0256_approval_export_to_mooring_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='fee_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mooringlicensing.FeeItem'),
        ),
    ]
