# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-09-20 03:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0257_approval_fee_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approval',
            name='fee_item',
        ),
        migrations.AddField(
            model_name='approval',
            name='fee_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mooringlicensing.FeePeriod'),
        ),
    ]
