# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-09-20 03:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0258_auto_20210920_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approval',
            name='fee_period',
        ),
    ]
