# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-10-06 01:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0262_applicationfee_fee_items_additional_aa'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeItemApplicationFee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mooringlicensing.ApplicationFee')),
                ('fee_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mooringlicensing.FeeItem')),
                ('vessel_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mooringlicensing.VesselDetails')),
            ],
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='key',
            field=models.CharField(choices=[('dcv_permit_template_file', 'DcvPermit template file'), ('dcv_admission_template_file', 'DcvAdmission template file'), ('wla_template_file', 'Waiting List Allocation template file'), ('aap_template_file', 'Annual Admission Permit template file'), ('aup_template_file', 'Authorised User Permit template file'), ('ml_template_file', 'Mooring Licence template file'), ('minimum_vessel_length', 'Minimum vessel length'), ('minimum_mooring_vessel_length', 'Minimum mooring vessel length'), ('min_sticker_number_for_dcv_permit', 'Minimun sticker number for DCV Permit')], max_length=255),
        ),
        migrations.AddField(
            model_name='applicationfee',
            name='fee_items_aa',
            field=models.ManyToManyField(related_name='application_fees_for_aa', through='mooringlicensing.FeeItemApplicationFee', to='mooringlicensing.FeeItem'),
        ),
    ]
