# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-10-06 01:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0264_remove_applicationfee_fee_items_additional_aa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicationfee',
            old_name='fee_items_aa',
            new_name='fee_items_for_aa',
        ),
    ]
