# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-10-07 04:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0265_auto_20211006_0958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationfee',
            name='fee_items',
        ),
    ]
