# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-10-12 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0268_merge_20211012_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vesselownership',
            name='mooring_licence_end_date',
        ),
        migrations.RemoveField(
            model_name='vesselownershiponapproval',
            name='sticker',
        ),
        migrations.AddField(
            model_name='approval',
            name='vessel_ownerships',
            field=models.ManyToManyField(through='mooringlicensing.VesselOwnershipOnApproval', to='mooringlicensing.VesselOwnership'),
        ),
    ]
