# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-10-20 06:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0271_delete_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approval',
            name='extended',
        ),
        migrations.RemoveField(
            model_name='compliance',
            name='submitter',
        ),
    ]
