# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-10-19 01:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0270_auto_20211015_1308'),
        ('mooringlicensing', '0271_delete_question'),
    ]

    operations = [
    ]
