# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-10-19 04:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0272_merge_20211019_0905'),
        ('mooringlicensing', '0271_auto_20211018_0857'),
    ]

    operations = [
    ]
