# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-03-09 06:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0276_auto_20211105_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='fee_season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mooringlicensing.FeeSeason'),
        ),
    ]
