# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-03-16 01:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0280_sticker_sticker_to_replace'),
        ('mooringlicensing', '0278_proposal_keep_existing_vessel'),
    ]

    operations = [
    ]
