# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-03-28 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0284_auto_20220321_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='listed_moorings',
            field=models.ManyToManyField(related_name='proposal_moorings_list', to='mooringlicensing.Mooring'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='listed_vessels',
            field=models.ManyToManyField(related_name='proposal_vessels_list', to='mooringlicensing.VesselOwnership'),
        ),
    ]
