# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-05-03 08:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0288_proposal_auto_approve'),
        ('mooringlicensing', '0290_auto_20220427_1339'),
    ]

    operations = [
    ]
