# Generated by Django 3.2.18 on 2023-03-20 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0300_auto_20230320_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposalapplicant',
            name='country',
        ),
        migrations.RemoveField(
            model_name='proposalapplicant',
            name='hash',
        ),
        migrations.RemoveField(
            model_name='proposalapplicant',
            name='line1',
        ),
        migrations.RemoveField(
            model_name='proposalapplicant',
            name='line2',
        ),
        migrations.RemoveField(
            model_name='proposalapplicant',
            name='line3',
        ),
        migrations.RemoveField(
            model_name='proposalapplicant',
            name='locality',
        ),
        migrations.RemoveField(
            model_name='proposalapplicant',
            name='postcode',
        ),
        migrations.RemoveField(
            model_name='proposalapplicant',
            name='search_text',
        ),
        migrations.RemoveField(
            model_name='proposalapplicant',
            name='state',
        ),
    ]
