# Generated by Django 3.2.18 on 2023-03-22 03:37

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0302_auto_20230322_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalapplicant',
            name='postal_country',
            field=django_countries.fields.CountryField(blank=True, default='AU', max_length=2),
        ),
        migrations.AddField(
            model_name='proposalapplicant',
            name='postal_line1',
            field=models.CharField(blank=True, max_length=255, verbose_name='Line 1'),
        ),
        migrations.AddField(
            model_name='proposalapplicant',
            name='postal_line2',
            field=models.CharField(blank=True, max_length=255, verbose_name='Line 2'),
        ),
        migrations.AddField(
            model_name='proposalapplicant',
            name='postal_line3',
            field=models.CharField(blank=True, max_length=255, verbose_name='Line 3'),
        ),
        migrations.AddField(
            model_name='proposalapplicant',
            name='postal_locality',
            field=models.CharField(blank=True, max_length=255, verbose_name='Suburb / Town'),
        ),
        migrations.AddField(
            model_name='proposalapplicant',
            name='postal_postcode',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='proposalapplicant',
            name='postal_state',
            field=models.CharField(blank=True, default='WA', max_length=255),
        ),
    ]
