# Generated by Django 3.2.18 on 2023-03-22 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0303_auto_20230322_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalapplicant',
            name='first_name',
            field=models.CharField(blank=True, max_length=128, verbose_name='Given name(s)'),
        ),
        migrations.AlterField(
            model_name='proposalapplicant',
            name='last_name',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
