# Generated by Django 3.2.18 on 2023-03-22 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0304_auto_20230322_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalapplicant',
            name='postal_same_as_residential',
            field=models.NullBooleanField(default=False),
        ),
    ]
