# Generated by Django 3.2.18 on 2023-03-23 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0305_proposalapplicant_postal_same_as_residential'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalapplicant',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='date of birth'),
        ),
    ]
