# Generated by Django 3.2.18 on 2023-03-23 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0306_proposalapplicant_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalapplicant',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='proposalapplicant',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='mobile number'),
        ),
        migrations.AddField(
            model_name='proposalapplicant',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='phone number'),
        ),
    ]
