# Generated by Django 3.2.18 on 2023-05-22 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0307_auto_20230323_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annualadmissionpermit',
            name='approval',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mooringlicensing.approval'),
        ),
        migrations.AlterField(
            model_name='applicationfee',
            name='proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application_fees', to='mooringlicensing.proposal'),
        ),
        migrations.AlterField(
            model_name='approval',
            name='org_applicant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_approvals', to='mooringlicensing.organisation'),
        ),
        migrations.AlterField(
            model_name='approvaluseraction',
            name='approval',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='mooringlicensing.approval'),
        ),
        migrations.AlterField(
            model_name='authoriseduserpermit',
            name='approval',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mooringlicensing.approval'),
        ),
        migrations.AlterField(
            model_name='compliance',
            name='approval',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliances', to='mooringlicensing.approval'),
        ),
        migrations.AlterField(
            model_name='compliance',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliances', to='mooringlicensing.proposal'),
        ),
        migrations.AlterField(
            model_name='compliancelogdocument',
            name='log_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='mooringlicensing.compliancelogentry'),
        ),
        migrations.AlterField(
            model_name='comprequest',
            name='compliance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mooringlicensing.compliance'),
        ),
        migrations.AlterField(
            model_name='dcvadmissionarrival',
            name='fee_constructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dcv_admission_arrivals', to='mooringlicensing.feeconstructor'),
        ),
        migrations.AlterField(
            model_name='dcvadmissiondocument',
            name='dcv_admission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='mooringlicensing.dcvadmission'),
        ),
        migrations.AlterField(
            model_name='dcvadmissionfee',
            name='dcv_admission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dcv_admission_fees', to='mooringlicensing.dcvadmission'),
        ),
        migrations.AlterField(
            model_name='dcvpermitdocument',
            name='dcv_permit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permits', to='mooringlicensing.dcvpermit'),
        ),
        migrations.AlterField(
            model_name='dcvpermitfee',
            name='dcv_permit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dcv_permit_fees', to='mooringlicensing.dcvpermit'),
        ),
        migrations.AlterField(
            model_name='feeconstructor',
            name='application_type',
            field=models.ForeignKey(limit_choices_to={'fee_by_fee_constructor': True}, on_delete=django.db.models.deletion.CASCADE, to='mooringlicensing.applicationtype'),
        ),
        migrations.AlterField(
            model_name='feeconstructor',
            name='vessel_size_category_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_constructors', to='mooringlicensing.vesselsizecategorygroup'),
        ),
        migrations.AlterField(
            model_name='mooringlicence',
            name='approval',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mooringlicensing.approval'),
        ),
        migrations.AlterField(
            model_name='waitinglistallocation',
            name='approval',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mooringlicensing.approval'),
        ),
    ]
