# Generated by Django 3.2.18 on 2023-05-19 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0309_auto_20230517_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='vesselregistrationdocument',
            name='original_file_ext',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vesselregistrationdocument',
            name='original_file_name',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='vesselregistrationdocument',
            name='proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_vessel_registration_documents', to='mooringlicensing.proposal'),
        ),
    ]
