# Generated by Django 3.2.18 on 2023-05-19 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0310_auto_20230519_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vesselregistrationdocument',
            name='vessel_ownership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vessel_registration_documents', to='mooringlicensing.vesselownership'),
        ),
    ]
