# Generated by Django 3.2.18 on 2023-05-22 05:19

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0311_alter_vesselregistrationdocument_vessel_ownership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vesselregistrationdocument',
            name='_file',
            field=models.FileField(max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/secure-media/', location='/home/katsufumishibata/dbca_source/mooringlicensing/secure-media'), upload_to=''),
        ),
    ]
