# Generated by Django 3.2.18 on 2023-05-23 02:34

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0313_alter_vesselregistrationdocument__file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vesselregistrationdocument',
            name='_file',
            field=models.FileField(max_length=512, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/home/katsufumishibata/dbca_source/mooringlicensing/private-media'), upload_to=''),
        ),
    ]
