# Generated by Django 3.2.18 on 2023-05-23 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0308_auto_20230522_1030'),
        ('mooringlicensing', '0314_alter_vesselregistrationdocument__file'),
    ]

    operations = [
    ]
