# Generated by Django 3.2.20 on 2023-07-21 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0315_merge_20230523_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='internal_status',
            field=models.CharField(blank=True, choices=[('waiting', 'Waiting for offer'), ('offered', 'Mooring Site Licence offered'), ('submitted', 'Mooring Site Licence application submitted')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='key',
            field=models.CharField(choices=[('dcv_permit_template_file', 'DcvPermit template file'), ('dcv_admission_template_file', 'DcvAdmission template file'), ('wla_template_file', 'Waiting List Allocation template file'), ('aap_template_file', 'Annual Admission Permit template file'), ('aup_template_file', 'Authorised User Permit template file'), ('ml_template_file', 'Mooring Site Licence template file'), ('ml_au_list_template_file', 'Mooring Site Licence Authorised User Summary template file'), ('minimum_vessel_length', 'Minimum vessel length'), ('minimum_mooring_vessel_length', 'Minimum mooring vessel length'), ('min_sticker_number_for_dcv_permit', 'Minimun sticker number for DCV Permit'), ('external_dashboard_sections_list', 'External dashboard sections list')], max_length=255),
        ),
        migrations.CreateModel(
            name='BackToAssessor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField(blank=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mooringlicensing.proposal')),
            ],
        ),
    ]
