# Generated by Django 3.2.20 on 2023-07-21 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0316_auto_20230721_1531'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BackToAssessor',
        ),
    ]
