# Generated by Django 3.2.20 on 2023-08-23 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0318_alter_admissiontype_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='dcvvessel',
            name='dcv_organisations',
            field=models.ManyToManyField(related_name='dcv_vessels', to='mooringlicensing.DcvOrganisation'),
        ),
    ]
