# Generated by Django 3.2.20 on 2023-08-23 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0319_dcvvessel_dcv_organisations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dcvvessel',
            name='dcv_organisation',
        ),
        migrations.AddField(
            model_name='dcvadmission',
            name='dcv_organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dcv_admissions', to='mooringlicensing.dcvorganisation'),
        ),
    ]
