# Generated by Django 3.2.20 on 2023-08-24 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0320_auto_20230823_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dcvpermit',
            name='lodgement_number',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
