# Generated by Django 3.2.20 on 2023-08-29 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0322_auto_20230829_1045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mooringreportdocument',
            name='proposal',
        ),
        migrations.RemoveField(
            model_name='signedlicenceagreementdocument',
            name='proposal',
        ),
        migrations.RemoveField(
            model_name='writtenproofdocument',
            name='proposal',
        ),
        migrations.CreateModel(
            name='ProposalWrittenProofDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mooringlicensing.proposal')),
                ('written_proof_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mooringlicensing.writtenproofdocument')),
            ],
        ),
        migrations.CreateModel(
            name='ProposalSignedLicenceAgreementDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mooringlicensing.proposal')),
                ('signed_licence_agreement_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mooringlicensing.signedlicenceagreementdocument')),
            ],
        ),
        migrations.CreateModel(
            name='ProposalMooringReportDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('mooring_report_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mooringlicensing.mooringreportdocument')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mooringlicensing.proposal')),
            ],
        ),
        migrations.AddField(
            model_name='proposal',
            name='mooring_report_documents',
            field=models.ManyToManyField(through='mooringlicensing.ProposalMooringReportDocument', to='mooringlicensing.MooringReportDocument'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='signed_licence_agreement_documents',
            field=models.ManyToManyField(through='mooringlicensing.ProposalSignedLicenceAgreementDocument', to='mooringlicensing.SignedLicenceAgreementDocument'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='written_proof_documents',
            field=models.ManyToManyField(through='mooringlicensing.ProposalWrittenProofDocument', to='mooringlicensing.WrittenProofDocument'),
        ),
    ]
