# Generated by Django 3.2.20 on 2023-09-08 00:56

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0325_vesselownership_company_ownerships'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vesselregistrationdocument',
            name='_file',
            field=models.FileField(max_length=512, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/data/data/projects/mooringlicensing/private-media'), upload_to=''),
        ),
    ]
