# Generated by Django 3.2.20 on 2023-09-08 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0326_alter_vesselregistrationdocument__file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vesselownership',
            name='company_ownership',
        ),
    ]
