# Generated by Django 3.2.20 on 2023-09-13 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0328_auto_20230913_1045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vesselownership',
            old_name='company_ownerships2',
            new_name='company_ownerships',
        ),
    ]
