# Generated by Django 3.2.20 on 2023-09-14 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0329_rename_company_ownerships2_vesselownership_company_ownerships'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyownership',
            name='status',
        ),
    ]
