# Generated by Django 3.2.20 on 2023-09-22 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0330_remove_companyownership_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sticker',
            options={'ordering': ['-date_updated', '-date_created']},
        ),
        migrations.AddField(
            model_name='sticker',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='sticker',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
