# Generated by Django 3.2.20 on 2023-10-06 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0331_auto_20230922_1042'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sticker',
            options={'ordering': ['-date_updated', '-date_created', '-number']},
        ),
        migrations.AlterModelOptions(
            name='vesselownership',
            options={'verbose_name_plural': 'Vessel Ownership'},
        ),
        migrations.AddField(
            model_name='stickeractiondetail',
            name='waive_the_fee',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='approval',
            name='internal_status',
            field=models.CharField(blank=True, choices=[('waiting', 'Waiting for offer'), ('offered', 'Mooring Site Licence offered'), ('submitted', 'Mooring Site Licence application submitted'), ('approved', 'Mooring Site Licence application approved')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='key',
            field=models.CharField(choices=[('dcv_permit_template_file', 'DcvPermit template file'), ('dcv_admission_template_file', 'DcvAdmission template file'), ('wla_template_file', 'Waiting List Allocation template file'), ('aap_template_file', 'Annual Admission Permit template file'), ('aup_template_file', 'Authorised User Permit template file'), ('ml_template_file', 'Mooring Site Licence template file'), ('ml_au_list_template_file', 'Mooring Site Licence Authorised User Summary template file'), ('minimum_vessel_length', 'Minimum vessel length'), ('minimum_mooring_vessel_length', 'Minimum mooring vessel length'), ('min_sticker_number_for_dcv_permit', 'Minimun sticker number for DCV Permit'), ('external_dashboard_sections_list', 'External dashboard sections list'), ('number_of_moorings_to_return_for_lookup', 'Number of moorings to return for lookup')], max_length=255),
        ),
    ]
