# Generated by Django 3.2.20 on 2023-10-10 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0332_auto_20231006_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalapplicant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='proposalapplicant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
