# Generated by Django 3.2.23 on 2024-01-12 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0334_proposal_declined_by_endorser'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationfee',
            name='handled_in_preload',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
