# Generated by Django 5.0.7 on 2024-08-07 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0337_auto_20240806_1124'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSystemSettings',
        ),
    ]
