# Generated by Django 5.0.8 on 2024-08-14 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0339_alter_proposalapplicant_proposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalapplicant',
            name='email_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
