# Generated by Django 5.0.8 on 2024-08-14 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0340_proposalapplicant_email_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalapplicant',
            name='proposal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposal_applicant', to='mooringlicensing.proposal'),
        ),
    ]
