# Generated by Django 5.0.8 on 2024-08-14 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0339_alter_proposalapplicant_first_name_and_more'),
        ('mooringlicensing', '0341_alter_proposalapplicant_proposal'),
    ]

    operations = [
    ]
