# Generated by Django 5.0.8 on 2024-08-20 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0340_mooringonapproval_active'),
        ('mooringlicensing', '0342_merge_20240814_1540'),
    ]

    operations = [
    ]
