# Generated by Django 5.0.8 on 2024-08-22 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0343_merge_20240820_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalapplicant',
            name='postal_locality',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Suburb / Town'),
        ),
    ]
