# Generated by Django 5.0.8 on 2024-08-29 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0344_alter_proposalapplicant_postal_locality'),
    ]

    operations = [
        migrations.AddField(
            model_name='dcvadmission',
            name='applicant',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
