# Generated by Django 5.0.9 on 2024-09-05 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0345_dcvadmission_applicant'),
    ]

    operations = [
        migrations.AddField(
            model_name='dcvpermit',
            name='applicant',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
