# Generated by Django 5.0.9 on 2024-09-09 03:31

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0345_dcvadmission_applicant'),
    ]

    operations = [
        migrations.AddField(
            model_name='sticker',
            name='postal_country',
            field=django_countries.fields.CountryField(blank=True, default='AU', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='sticker',
            name='postal_line1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Line 1'),
        ),
        migrations.AddField(
            model_name='sticker',
            name='postal_line2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Line 2'),
        ),
        migrations.AddField(
            model_name='sticker',
            name='postal_line3',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Line 3'),
        ),
        migrations.AddField(
            model_name='sticker',
            name='postal_locality',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Suburb / Town'),
        ),
        migrations.AddField(
            model_name='sticker',
            name='postal_postcode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='sticker',
            name='postal_state',
            field=models.CharField(blank=True, default='WA', max_length=255, null=True),
        ),
    ]
