# Generated by Django 5.0.9 on 2024-09-09 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0346_sticker_postal_country_sticker_postal_line1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sticker',
            old_name='postal_country',
            new_name='postal_address_country',
        ),
        migrations.RenameField(
            model_name='sticker',
            old_name='postal_line1',
            new_name='postal_address_line1',
        ),
        migrations.RenameField(
            model_name='sticker',
            old_name='postal_line2',
            new_name='postal_address_line2',
        ),
        migrations.RenameField(
            model_name='sticker',
            old_name='postal_line3',
            new_name='postal_address_line3',
        ),
        migrations.RenameField(
            model_name='sticker',
            old_name='postal_locality',
            new_name='postal_address_locality',
        ),
        migrations.RenameField(
            model_name='sticker',
            old_name='postal_postcode',
            new_name='postal_address_postcode',
        ),
        migrations.RenameField(
            model_name='sticker',
            old_name='postal_state',
            new_name='postal_address_state',
        ),
    ]
