# Generated by Django 5.0.9 on 2024-09-09 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0347_dcvpermit_country_dcvpermit_line1_dcvpermit_line2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dcvadmission',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='dcvadmission',
            name='status',
            field=models.CharField(blank=True, choices=[('paid', 'Paid'), ('unpaid', 'Unpaid')], max_length=40, null=True),
        ),
    ]
