# Generated by Django 5.0.9 on 2024-09-09 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0348_dcvadmission_date_created_dcvadmission_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dcvadmission',
            name='status',
            field=models.CharField(blank=True, choices=[('paid', 'Paid'), ('unpaid', 'Unpaid'), ('cancelled', 'Cancelled')], max_length=40, null=True),
        ),
    ]
