# Generated by Django 5.0.9 on 2024-09-10 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0349_alter_dcvadmission_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dcvpermit',
            old_name='country',
            new_name='postal_address_country',
        ),
        migrations.RenameField(
            model_name='dcvpermit',
            old_name='line1',
            new_name='postal_address_line1',
        ),
        migrations.RenameField(
            model_name='dcvpermit',
            old_name='line2',
            new_name='postal_address_line2',
        ),
        migrations.RenameField(
            model_name='dcvpermit',
            old_name='line3',
            new_name='postal_address_line3',
        ),
        migrations.RenameField(
            model_name='dcvpermit',
            old_name='postcode',
            new_name='postal_address_postcode',
        ),
        migrations.RenameField(
            model_name='dcvpermit',
            old_name='state',
            new_name='postal_address_state',
        ),
        migrations.RenameField(
            model_name='dcvpermit',
            old_name='locality',
            new_name='postal_address_suburb',
        ),
    ]
