# Generated by Django 5.0.9 on 2024-09-11 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0348_stickeractiondetail_change_sticker_address_and_more'),
        ('mooringlicensing', '0349_alter_dcvadmission_status'),
    ]

    operations = [
    ]
