# Generated by Django 5.0.9 on 2024-09-11 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0348_stickeractiondetail_change_sticker_address_and_more'),
        ('mooringlicensing', '0350_rename_country_dcvpermit_postal_address_country_and_more'),
    ]

    operations = [
    ]
