# Generated by Django 5.0.9 on 2024-09-11 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0351_merge_20240911_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='expiry_notice_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Number of times an Expiry Notice has been sent'),
        ),
    ]
