# Generated by Django 5.0.9 on 2024-09-12 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0350_merge_20240911_1124'),
        ('mooringlicensing', '0352_approval_expiry_notice_count'),
    ]

    operations = [
    ]
