# Generated by Django 5.0.9 on 2024-09-12 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0353_merge_20240912_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalSiteLicenseeMooringRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_licensee_email', models.CharField(blank=True, max_length=200, null=True)),
                ('endorser_reminder_sent', models.BooleanField(default=False)),
                ('declined_by_endorser', models.BooleanField(default=False)),
                ('mooring', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mooringlicensing.mooring')),
                ('proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_licensee_mooring_request', to='mooringlicensing.proposal')),
            ],
        ),
    ]
