# Generated by Django 5.0.9 on 2024-09-13 05:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0354_proposalsitelicenseemooringrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalsitelicenseemooringrequest',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='proposalsitelicenseemooringrequest',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
