# Generated by Django 5.0.9 on 2024-09-13 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0355_proposalsitelicenseemooringrequest_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalsitelicenseemooringrequest',
            name='mooring',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mooringlicensing.mooring'),
        ),
        migrations.AlterField(
            model_name='proposalsitelicenseemooringrequest',
            name='proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_licensee_mooring_request', to='mooringlicensing.proposal'),
        ),
    ]
