# Generated by Django 5.0.9 on 2024-09-20 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0358_remove_proposal_declined_by_endorser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalsitelicenseemooringrequest',
            name='mooring',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_licensee_mooring_request', to='mooringlicensing.mooring'),
        ),
    ]
