# Generated by Django 5.0.9 on 2024-10-03 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0361_alter_globalsettings_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approval',
            name='expiry_notice_count',
        ),
        migrations.RemoveField(
            model_name='approval',
            name='expiry_notice_sent',
        ),
        migrations.AddField(
            model_name='proposal',
            name='invitee_reminder_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
