# Generated by Django 5.0.9 on 2024-10-15 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0362_remove_organisationaction_organisation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='approval_level_document',
        ),
        migrations.DeleteModel(
            name='RequirementDocument',
        ),
    ]
