# Generated by Django 5.0.9 on 2024-10-10 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0362_remove_approval_expiry_notice_count_and_more'),
        ('mooringlicensing', '0362_remove_organisationaction_organisation_and_more'),
    ]

    operations = [
    ]
