# Generated by Django 5.0.9 on 2024-10-16 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0363_merge_20241010_1649'),
        ('mooringlicensing', '0363_remove_proposal_approval_level_document_and_more'),
    ]

    operations = [
    ]
