# Generated by Django 5.0.9 on 2024-10-17 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0364_merge_20241016_0843'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HelpPage',
        ),
        migrations.DeleteModel(
            name='PreviewTempApproval',
        ),
    ]
