# Generated by Django 5.0.9 on 2024-10-23 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0366_remove_approval_cover_letter_document_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposalapplicant',
            old_name='postal_country',
            new_name='postal_address_country',
        ),
        migrations.RenameField(
            model_name='proposalapplicant',
            old_name='postal_line1',
            new_name='postal_address_line1',
        ),
        migrations.RenameField(
            model_name='proposalapplicant',
            old_name='postal_line2',
            new_name='postal_address_line2',
        ),
        migrations.RenameField(
            model_name='proposalapplicant',
            old_name='postal_line3',
            new_name='postal_address_line3',
        ),
        migrations.RenameField(
            model_name='proposalapplicant',
            old_name='postal_locality',
            new_name='postal_address_locality',
        ),
        migrations.RenameField(
            model_name='proposalapplicant',
            old_name='postal_postcode',
            new_name='postal_address_postcode',
        ),
        migrations.RenameField(
            model_name='proposalapplicant',
            old_name='postal_state',
            new_name='postal_address_state',
        ),
        migrations.RenameField(
            model_name='proposalapplicant',
            old_name='residential_country',
            new_name='residential_address_country',
        ),
        migrations.RenameField(
            model_name='proposalapplicant',
            old_name='residential_line1',
            new_name='residential_address_line1',
        ),
        migrations.RenameField(
            model_name='proposalapplicant',
            old_name='residential_line2',
            new_name='residential_address_line2',
        ),
        migrations.RenameField(
            model_name='proposalapplicant',
            old_name='residential_line3',
            new_name='residential_address_line3',
        ),
        migrations.RenameField(
            model_name='proposalapplicant',
            old_name='residential_locality',
            new_name='residential_address_locality',
        ),
        migrations.RenameField(
            model_name='proposalapplicant',
            old_name='residential_postcode',
            new_name='residential_address_postcode',
        ),
        migrations.RenameField(
            model_name='proposalapplicant',
            old_name='residential_state',
            new_name='residential_address_state',
        ),
        migrations.RemoveField(
            model_name='proposalapplicant',
            name='postal_same_as_residential',
        ),
    ]
