# Generated by Django 5.0.9 on 2024-10-24 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0367_rename_postal_country_proposalapplicant_postal_address_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyownership',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='companyownership',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='approval_level',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='assessor_data',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='comment_data',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='lodgement_sequence',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='personal_details',
        ),
    ]
