# Generated by Django 5.0.9 on 2024-10-24 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0368_remove_companyownership_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compliance',
            name='fee_invoice_reference',
        ),
        migrations.RemoveField(
            model_name='compliance',
            name='num_participants',
        ),
        migrations.RemoveField(
            model_name='proposalstandardrequirement',
            name='participant_number_required',
        ),
    ]
