# Generated by Django 5.0.9 on 2024-10-24 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0369_remove_compliance_fee_invoice_reference_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comprequest',
            name='compliance',
        ),
        migrations.DeleteModel(
            name='ComplianceAmendmentRequest',
        ),
        migrations.DeleteModel(
            name='CompRequest',
        ),
    ]
