# Generated by Django 5.0.9 on 2024-10-24 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0370_remove_comprequest_compliance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceAmendmentRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('amended', 'Amended')], default='requested', max_length=30, verbose_name='Status')),
                ('text', models.TextField(blank=True)),
                ('compliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mooringlicensing.compliance')),
                ('reason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mooringlicensing.complianceamendmentreason')),
            ],
        ),
    ]
