# Generated by Django 5.0.9 on 2024-10-29 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0371_complianceamendmentrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TemporaryDocument',
        ),
        migrations.DeleteModel(
            name='TemporaryDocumentCollection',
        ),
    ]
