# Generated by Django 5.0.9 on 2024-10-29 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0372_delete_temporarydocument_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approval',
            name='exported',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='approval_comment',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='prev_processing_status',
        ),
        migrations.RemoveField(
            model_name='vesseldetails',
            name='exported',
        ),
        migrations.RemoveField(
            model_name='vesselownership',
            name='exported',
        ),
    ]
