# Generated by Django 5.0.9 on 2024-11-28 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0373_remove_approval_exported_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dcvpermit',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
