# Generated by Django 5.0.9 on 2024-11-28 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0374_dcvpermit_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='dcvpermit',
            name='status',
            field=models.CharField(blank=True, choices=[('current', 'Current'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], max_length=40, null=True),
        ),
    ]
