# Generated by Django 5.0.9 on 2024-11-29 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0376_proposal_payment_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='payment_reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
