# Generated by Django 5.0.9 on 2024-12-09 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0377_proposal_payment_reminder_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='no_email_notifications',
            field=models.BooleanField(default=False),
        ),
    ]
