# Generated by Django 5.0.9 on 2024-12-31 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0378_proposal_no_email_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='invoice_property_cache',
            field=models.JSONField(blank=True, default={}, null=True),
        ),
    ]
