# Generated by Django 5.0.9 on 2025-01-02 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0379_proposal_invoice_property_cache'),
    ]

    operations = [
        migrations.AddField(
            model_name='dcvadmission',
            name='invoice_property_cache',
            field=models.JSONField(blank=True, default={}, null=True),
        ),
    ]
