# Generated by Django 5.0.9 on 2025-01-06 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0382_sticker_invoice_property_cache'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposaltype',
            name='code',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
