# Generated by Django 5.0.9 on 2025-01-17 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0383_insurancecertificatedocument_copied'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurancecertificatedocument',
            name='copied',
        ),
    ]
