# Generated by Django 5.0.9 on 2025-01-15 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0386_applicationfee_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dcvadmission',
            name='invoice_property_cache',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='dcvpermit',
            name='invoice_property_cache',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='invoice_property_cache',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='sticker',
            name='invoice_property_cache',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
