# Generated by Django 5.0.11 on 2025-01-16 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0387_alter_dcvadmission_invoice_property_cache_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sticker',
            name='status_before_cancelled',
            field=models.CharField(choices=[('ready', 'Ready'), ('not_ready_yet', 'Not Ready Yet'), ('awaiting_printing', 'Awaiting Printing'), ('current', 'Current'), ('to_be_returned', 'To be Returned'), ('returned', 'Returned'), ('lost', 'Lost'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='ready', max_length=40),
        ),
    ]
