# Generated by Django 5.0.11 on 2025-01-16 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0388_sticker_status_before_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='mooringonapproval',
            name='previous_sticker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_sticker', to='mooringlicensing.sticker'),
        ),
    ]
