# Generated by Django 5.0.11 on 2025-01-20 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0384_remove_insurancecertificatedocument_copied'),
        ('mooringlicensing', '0390_alter_sticker_status_before_cancelled'),
    ]

    operations = [
    ]
