# Generated by Django 5.0.11 on 2025-01-23 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0391_merge_20250120_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='reissue_vessel_properties',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
