# Generated by Django 5.0.11 on 2025-01-28 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0392_proposal_reissue_vessel_properties'),
    ]

    operations = [
        migrations.AddField(
            model_name='stickeractiondetail',
            name='approval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sticker_action_approval', to='mooringlicensing.approval'),
        ),
    ]
