# Generated by Django 5.2 on 2025-04-23 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0393_stickeractiondetail_approval'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileExtensionWhitelist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The file extension without the dot, e.g. jpg, pdf, docx, etc', max_length=16)),
                ('model', models.CharField(default='all', max_length=255)),
            ],
            options={
                'unique_together': {('name', 'model')},
            },
        ),
    ]
