# Generated by Django 5.1.8 on 2025-05-13 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0394_fileextensionwhitelist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mooringonapproval',
            name='mooring',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mooring_on_approval', to='mooringlicensing.mooring'),
        ),
    ]
