# Generated by Django 5.2.4 on 2025-07-22 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0395_alter_mooringonapproval_mooring'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationfee',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mooring',
            name='vessel_draft_limit',
            field=models.DecimalField(decimal_places=2, default='0.00', help_text='Any required changes should be done via Mooring Bookings.', max_digits=8),
        ),
        migrations.AlterField(
            model_name='mooring',
            name='vessel_size_limit',
            field=models.DecimalField(decimal_places=2, default='0.00', help_text='Any required changes should be done via Mooring Bookings.', max_digits=8),
        ),
        migrations.AlterField(
            model_name='mooring',
            name='vessel_weight_limit',
            field=models.DecimalField(decimal_places=2, default='0.00', help_text='Any required changes should be done via Mooring Bookings.', max_digits=8),
        ),
    ]
