# Generated by Django 5.2.4 on 2025-08-19 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0396_applicationfee_cancelled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vesseldetails',
            name='vessel_name',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
