# Generated by Django 5.2.4 on 2025-09-02 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0397_alter_vesseldetails_vessel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='mooringonapproval',
            name='migrated',
            field=models.BooleanField(default=False),
        ),
    ]
