# Generated by Django 5.2.4 on 2025-10-06 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0399_approval_extension_details_alter_globalsettings_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='bypass_payment_reason',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
