# Generated by Django 5.2.8 on 2025-12-09 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0401_approval_created_at_approvalhistory_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='wla_order',
            field=models.PositiveIntegerField(blank=True, help_text='wla order per mooring bay', null=True),
        ),
    ]
